version: '3.8'

services:
  client:
    build:
      context: .
      target: stage
    image: client
    volumes:
      - ./:/app
    env_file:
      - .env.local
    restart: unless-stopped
    ports:
      - 3300:3300
